spring:
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9432/postgres
    username: ad-adm-local
    password: ad-adm-local